sudo: required
language: generic

services: 
    - docker 

before_install:
    - docker build -t my-docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true my-docker-react npm run test

deploy:
    provide: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env" 
    bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-120682433586"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
